- name: variables from inventory
  hosts: localhost
  tasks:
  - name: Print information
    vars:
      Trainer: "Satya Narayana Y V"
      timings: "07:15 AM IST"
    ansible.builtin.debug:
      msg: "Hi, We are learning devops from Trainer {{Trainer}}, Duration is {{timings}}"