- name: variable preference
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: check preference 
    # vars:
    # Wishes: "Morning from TASK variable"
    ansible.builtin.debug:
      msg: "Hello, Good {{WISHES}}"